[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 500
evm_version = "paris"
via_ir = true
bytecode_hash = "ipfs"
fs_permissions = [{ access = "read", path = "./deployments" }, { access = "write", path = "./deployments" }]

[profile.local]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
via_ir = true
bytecode_hash = "ipfs"
fs_permissions = [{ access = "read", path = "./deployments" }, { access = "write", path = "./deployments" }]
ignore_eip_3860 = true
# Note: AppFactory is ~26KB (over EIP-170 limit) but Anvil deploys it anyway
# This is fine for local dev - optimize before mainnet deployment

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
quote_style = "double"
number_underscore = "preserve"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
base_sepolia = { key = "${BASESCAN_API_KEY}" }