/**
 * Auto-generated Contract Configuration
 * 
 * Generated by: scripts/generate-config.ts
 * Source: deployments/local.json
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 */

export const CHAIN_ID = 31337;
export const RPC_URL = 'http://127.0.0.1:8545';

export const contracts = {
  // Core Protocol
  ELTA: '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512' as const,
  ElataXP: '0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0' as const,
  VeELTA: '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9' as const,
  LotPool: '0x0165878A594ca255338adfa4d48449f69242Eb8F' as const,
  RewardsDistributor: '0xa513E6E4b8f2a923D98304ec87F64353C4D5C853' as const,
  ElataTimelock: '0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9' as const,
  ElataGovernor: '0x5FC8d32690cc91D4c39d9d3abcBD16989F875707' as const,
  
  // App Ecosystem
  AppFactory: '0x610178dA211FEF7D417bC0e6FeD39F05609AD788' as const,
  AppModuleFactory: '0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0' as const,
  TournamentFactory: '0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82' as const,
  
  // Mock DEX
  UniswapV2Factory: '0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6' as const,
  UniswapV2Router: '0x8A791620dd6260079BF849Dc5567aDC3F2FdC318' as const,
} as const;

export const testAccounts = [
  "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
  "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
  "0x90F79bf6EB2c4f870365E785982E1f101E93b906",
  "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65",
  "0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc"
] as const;

export type ContractName = keyof typeof contracts;
export type ContractAddress = typeof contracts[ContractName];

// Helper to get contract address by name
export function getContractAddress(name: ContractName): string {
  return contracts[name];
}

// Export deployment info
export const deploymentInfo = {
  network: 'localhost',
  chainId: 31337,
  deployer: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
  timestamp: new Date().toISOString(),
} as const;
