#!/bin/bash

# Elata Protocol Local Development Setup
set -e

echo "🚀 Setting up Elata Protocol for local development..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if we're in the right directory
if [ ! -f "foundry.toml" ]; then
    echo -e "${RED}❌ Please run this script from the elata-protocol directory${NC}"
    exit 1
fi

# Check if Anvil is running
if ! curl -s -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' http://127.0.0.1:8545 > /dev/null 2>&1; then
    echo -e "${YELLOW}⚠️  Anvil is not running. Starting Anvil...${NC}"
    echo "Please run 'anvil' in a separate terminal and press Enter to continue."
    read -p ""
else
    echo -e "${GREEN}✅ Anvil is running${NC}"
fi

# Build contracts
echo -e "${BLUE}🔨 Building contracts...${NC}"
forge build

# Deploy contracts to local network
echo -e "${BLUE}📦 Deploying contracts to Anvil...${NC}"
PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 \
forge script script/DeployLocal.s.sol:DeployLocal \
    --rpc-url http://127.0.0.1:8545 \
    --broadcast \
    --private-key $PRIVATE_KEY

echo -e "${GREEN}✅ Contracts deployed successfully!${NC}"

# App Store instructions
echo -e "${BLUE}🎨 App Store frontend (separate repo)${NC}"
echo "Clone elata-appstore next to elata-protocol, then:"
echo "  cd ../elata-appstore"
echo "  npm install"
echo "  # Generate local .env with contract addresses"
echo "  cd ../elata-protocol && npm run dev:config"
echo "  # Start the appstore connected to local Anvil"
echo "  cd ../elata-appstore && npm run local:full"

echo -e "${GREEN}🎉 Setup complete!${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo "1. Ensure elata-appstore/.env.local exists (generated by dev:config)"
echo "2. Get a Wallet Connect project ID (optional)"
echo "3. Import this private key into MetaMask: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
echo "4. Add localhost:8545 as a custom network in MetaMask (Chain ID: 31337)"
echo "5. Run 'npm run local:full' in elata-appstore"
echo ""
echo -e "${GREEN}Happy building! 🧠⚡${NC}"


