#!/usr/bin/env node

/**
 * Generate App Store Frontend Configuration from Deployment
 *
 * Reads deployments/local.json and generates:
 * - ../elata-appstore/.env.local (NEXT_PUBLIC_*_ADDRESS_LOCAL variables)
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface DeploymentConfig {
  network: string;
  chainId: number;
  deployer: string;
  contracts: {
    ELTA: string;
    ElataXP: string;
    VeELTA: string;
    LotPool: string;
    RewardsDistributor: string;
    ElataTimelock: string;
    ElataGovernor: string;
    AppFactory: string;
    AppModuleFactory: string;
    TournamentFactory: string;
    UniswapV2Factory: string;
    UniswapV2Router: string;
  };
  testAccounts: string[];
}

function main() {
  console.log('🔧 Generating appstore frontend configuration...\n');

  const projectRoot = join(__dirname, '..');
  const deploymentPath = join(projectRoot, 'deployments', 'local.json');
  // Target the sibling appstore repository
  const appstoreDir = join(projectRoot, '..', 'elata-appstore');
  
  // Check if deployment exists
  if (!existsSync(deploymentPath)) {
    console.error('❌ Error: deployments/local.json not found!');
    console.error('   Run deployment first: npm run dev:deploy');
    process.exit(1);
  }

  // Read deployment config
  const deployment: DeploymentConfig = JSON.parse(readFileSync(deploymentPath, 'utf-8'));

  if (!existsSync(appstoreDir)) {
    console.warn('⚠️  elata-appstore directory not found at:', appstoreDir);
    console.warn('   Skipping appstore .env.local generation. This is optional and only needed if you have access to the private frontend repo.');
    process.exit(0);
  }

  // Generate .env.local in elata-appstore
  generateEnvLocal(deployment, appstoreDir);

  console.log('\n✅ Appstore .env.local generated successfully!');
  console.log('\nFile created:');
  console.log('  - elata-appstore/.env.local');
}

function generateEnvLocal(deployment: DeploymentConfig, appstoreDir: string) {
  const env = `# Auto-generated by elata-protocol/scripts/generate-config.ts
# Local Development Environment for elata-appstore

# Network Configuration
NEXT_PUBLIC_CHAIN_ID=${deployment.chainId}
NEXT_PUBLIC_RPC_URL=http://127.0.0.1:8545

# Contract Addresses - Core Protocol (LOCAL)
NEXT_PUBLIC_ELTA_ADDRESS_LOCAL=${deployment.contracts.ELTA}
NEXT_PUBLIC_ELATA_XP_ADDRESS_LOCAL=${deployment.contracts.ElataXP}
NEXT_PUBLIC_VE_ELTA_ADDRESS_LOCAL=${deployment.contracts.VeELTA}
NEXT_PUBLIC_LOT_POOL_ADDRESS_LOCAL=${deployment.contracts.LotPool}
NEXT_PUBLIC_REWARDS_DISTRIBUTOR_ADDRESS_LOCAL=${deployment.contracts.RewardsDistributor}
NEXT_PUBLIC_ELATA_TIMELOCK_ADDRESS_LOCAL=${deployment.contracts.ElataTimelock}
NEXT_PUBLIC_ELATA_GOVERNOR_ADDRESS_LOCAL=${deployment.contracts.ElataGovernor}

# Contract Addresses - App Ecosystem (LOCAL)
NEXT_PUBLIC_APP_FACTORY_ADDRESS_LOCAL=${deployment.contracts.AppFactory}
NEXT_PUBLIC_APP_MODULE_FACTORY_ADDRESS_LOCAL=${deployment.contracts.AppModuleFactory}
NEXT_PUBLIC_TOURNAMENT_FACTORY_ADDRESS_LOCAL=${deployment.contracts.TournamentFactory}

# DEX Addresses (Mock Uniswap) (LOCAL)
NEXT_PUBLIC_UNISWAP_V2_FACTORY_ADDRESS_LOCAL=${deployment.contracts.UniswapV2Factory}
NEXT_PUBLIC_UNISWAP_V2_ROUTER_ADDRESS_LOCAL=${deployment.contracts.UniswapV2Router}

# Optional: WalletConnect (set your own if available)
# NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=your_project_id_here
`;

  const envPath = join(appstoreDir, '.env.local');
  writeFileSync(envPath, env);
  console.log('✓ Generated elata-appstore/.env.local');
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}

export { main as generateConfig };


